FROM wtaylor8/generic-scada:latest

COPY scada/manufacturing/ /app/scenarios/manufacturing/
COPY scada/manufacturing/templates/diagram_base.html /app/scada/templates/diagram_base.html
COPY scada/manufacturing/templates/diagrams/manufacturing_overview.html /app/scada/templates/diagrams/manufacturing_overview.html
