apiVersion: apps/v1
kind: Deployment
metadata:
  name: gns3-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gns3
  template:
    metadata:
      labels:
        app: gns3
    spec:
      hostNetwork: true  # Allows the container to use the host network
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: gns3-container
          image: cithit/gns3-project-deploy:latest
          imagePullPolicy: Always  # Ensures the latest image is always pulled
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
