apiVersion: apps/v1
kind: Deployment
metadata:
  name: gns3-deployment   # <-- Ensure this matches the name in Jenkins
  namespace: gns3         # <-- If using a namespace, it must match
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gns3
  template:
    metadata:
      labels:
        app: gns3
    spec:
      containers:
      - name: gns3-container  # <-- Ensure this matches in Jenkins
        image: cithit/gns3-project:latest
