FROM wtaylor8/generic-scada:latest

COPY scada/freshwater_treatment/ /app/scada/freshwater_treatment/
COPY scada/templates/diagrams/freshwater_overview.html /app/scada/templates/diagrams/freshwater_overview.html
