FROM wtaylor8/generic-scada:latest

COPY scada/traffic/ /app/scenarios/traffic/
COPY scada/traffic/templates/diagram_base.html /app/scada/templates/diagram_base.html
COPY scada/traffic/templates/diagrams/traffic_overview.html /app/scada/templates/diagrams/traffic_overview.html
