FROM wtaylor8/generic-scada:latest

COPY scada/module3/ /app/scenarios/traffic/
COPY scada/module3/templates/diagram_base.html /app/scada/templates/diagram_base.html
COPY scada/module3/templates/diagrams/traffic_overview.html /app/scada/templates/diagrams/traffic_overview.html
